<div class="story">

	<p>	Kill Devil Hills has an odd name  but the story behind it brings to life the folk history of the area. Rum was the drink of choice back in the colonial times. A ship wrecked on the shores of <a href="http://www.kdhnc.com/" title="Town Of Kill Devil Hills">Kill Devil Hills</a> laden with a shipment of rum. The locals scavenged the shipment, as was customary in those days, and hid the  rum behind the sand dunes where the Wright brothers later flew the first plane. The rum was strong enough to &quot;Kill the devil&quot; and those dunes where the rum was hidden was nicknamed Kill Devil Hill and the name has stuck like a sandspur.
	</p>
	<p>	On December 17, 1903,  Wilbur and Orville Wright made the first successful  power-driven airplane flight from the sand dune known as the Kill Devil Hill near the town of Kitty Hawk. History records the first flight in <a href="https://www.outerbankshome.com/outer banks/real estate/KittyHawk/" title="Kitty Hawk">Kitty Hawk</a> but the location of the flight was actually in Kill Devil Hills.
	</p>
	<p>Kill Devil Hills is the oldest town on the Outer Banks of North Carolina having incorporated  in 1953. Still a baby of a town compared to most localities across the US,  it is the most established town on the Outer Banks. Kill Devil Hills is comprised of 63 subdivisions/communities containing some 8,000+ parcels of which some 1,000 are vacant lots. According to the US Census Bureau, there are 10,500 year round residents. Kill Devil Hills has the highest percentage of year round residents of all the towns on the Outer Banks. This is where you will also find most of the restaurants, stores and ancillary services that a permanent population requires. There are also a large number of vacation homes making Kill Devil Hills the perfect location. </p>
	<p>	Bordered by Kitty Hawk on the north, <a href="https://www.outerbankshome.com/outer banks/real estate/nags head/" title="Nags Head">Nags Head</a> on the south, the Atlantic Ocean to the east and Kitty Hawk Bay to the west, Kill Devil Hills has  17 free public beach accesses on the ocean front, 2 sound accesses, 1 sound boat ramp, 2 children's play grounds, and a pleasant selection of beach houses. Kill Devil Hills is one of the most vacation friendly resort towns on the east coast.
	</p>
	<p>	To help make it easier for you, we have sorted the properties for sale   in Kill Devil Hills into convenient categories like investment homes, <a href="https://www.outerbankshome.com/outer banks/real estate/KillDevilHills/condos/" title="Kill Devil Hills Condos For sale">condos</a>, <a href="https://www.outerbankshome.com/outer banks/real estate/KillDevilHills/land/" title="Click HERE Kill Devil Hills Lots and land for sale">vacant land</a>, <a href="https://www.outerbankshome.com/outer banks/real estate/KillDevilHills/oceanfront/" title="Kill Devil Hills Oceanfront Homes For sale">oceanfront houses</a>, <a href="https://www.outerbankshome.com/outer banks/real estate/KillDevilHills/soundfront/" title="Kill Devil Hills Soundfront Homes For sale">houses located on the  Bay.</a>
	</p>
	<p>	The more information you have about the Kill Devil Hills real estate market, the easier it will be to make a decision about buying or selling. We have compiled the sold statistics for the Kill Devil Hills area going back to the year 2004. <a href="https://www.outerbankshome.com/outer banks/real estate/KillDevilHills/killdevilhills-homes-sold-statistics.asp" title="Kill Devil Hills Sold Home Statistics">Kill Devil Hills Sold Home Statistics</a>, <a href="https://www.outerbankshome.com/outer banks/real estate/KillDevilHills/killdevilhills-condos-sold-statistics.asp" title="Kill Devil Hills Sold Condo Statistics">Kill Devil Hills Sold Condo Statistics</a> and <a href="https://www.outerbankshome.com/outer banks/real estate/KillDevilHills/killdevilhills-land-sold-statistics.asp" title="Kill Devil Hills Sold Land Statistics">Kill Devil Hills Sold Land/Lot Statistics</a>. You can find the homes that sold recently in Kill Devil Hills <a href="https://www.outerbankshome.com/outer banks/real estate/KillDevilHills/sold/" title="Kill Devil Hills SOLD Homes">HERE</a>.
	</p>
</div>